version: "3.8"

services:
  bot:
    build: ./whatsapp
    container_name: wa-bot
    restart: unless-stopped
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
    networks:
      - nodered_influxdb_grafana
    volumes:
      - ./whatsapp:/usr/src/app

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - ./node-red-data:/data
    environment:
      - NODE_RED_ENABLE_PROJECTS=${NODE_RED_ENABLE_PROJECTS}
      - INFLUXDB_URL=http://influxdb:8086
    networks:
      - nodered_influxdb_grafana

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_INIT_ADMIN_TOKEN}
      - INFLUXDB_HTTP_CORS_ENABLED=true
      - INFLUXDB_HTTP_CORS_ORIGINS=*
    volumes:
      - ./influxdb-data:/var/lib/influxdb2
    networks:
      - nodered_influxdb_grafana

networks:
  nodered_influxdb_grafana:
    driver: bridge
